version: '3.8'

services:
  # Email.API - Microservice d'envoi d'emails
  email.api:
    image: email.api:latest
    build:
      context: .
      dockerfile: src/eshop.services/email/Email.API/Dockerfile
    container_name: email-api
    ports:
      - "6070:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SmtpSettings__Server=mailpit
      - SmtpSettings__Port=1025
      - SmtpSettings__Username=
      - SmtpSettings__Password=
      - SmtpSettings__EnableSsl=false
      - SmtpSettings__FromEmail=noreply@eshop.com
      - SmtpSettings__FromName=eShop YNOV
      - MessageBroker__Host=amqp://rabbitmq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - rabbitmq
      - mailpit
    networks:
      - eshop-network
    restart: unless-stopped

  # Mailpit - Serveur SMTP de d√©veloppement
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # WebUI
    networks:
      - eshop-network
    restart: unless-stopped

  # RabbitMQ - Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - eshop-network
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  eshop-network:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local
